MAKEFLAGS += --no-print-directory
SHELL = bash

.PHONY: all
all: check_requirements install_stuff ;

#
# Ensure prerequisites for executing various commands in hiden
#
.PHONY: check_requirements
check_requirements:
	@if [[ "$(abspath $(dir .))" != "$(abspath $(dir ~))" ]]; then echo "hiden must be at ~/hiden !"; exit 1; fi
	@if [[ "$(shell uname)" != "Darwin" ]]; then echo "Only supports macOS"; exit 1; fi
	@which -s brew curl git

#
# Install stuff!
#
.PHONY: install_stuff
install_stuff: user_bin brew_packages fish vim ssh install_fonts misc ;

### Custom scripts

.PHONY: user_bin
user_bin: ~/bin ~/bin/local_git_user ~/bin/imgcat ;

~/bin:
	mkdir -p ~/bin

~/bin/local_git_user:
	ln -Fs ~/hiden/bin/local_git_user ~/bin/local_git_user

~/bin/imgcat:
	ln -Fs ~/hiden/bin/imgcat ~/bin/imgcat

### Homebrew related

.PHONY: brew_packages
brew_packages:
	@# Installing or upgrading already installed ones using `brew bundle`
	@# If `brew bundle`'s automatic installation of Homebrew-bundle fails, try manually git-cloning the Homebrew-bundle repository!
	brew bundle --file=~/hiden/Brewfile
	gh completion -s fish > ~/.config/fish/completions/gh.fish
	gh auth login

### iTerm2 related

# It will upgrade itself to the latest version, after first boot
LATEST_ITERM_ZIP = iTerm2-3_1_5.zip
/Applications/iTerm.app:
	curl -O https://iterm2.com/downloads/stable/$(LATEST_ITERM_ZIP)
	unzip -q $(LATEST_ITERM_ZIP)
	sudo mv iTerm.app /Applications/.
	rm $(LATEST_ITERM_ZIP)

### fish related

.PHONY: fish
fish: fish_bin ~/.config/fish/functions/fisher.fish ~/.config/fish/config.fish fish_plugins set_shell ;

.PHONY: fish_bin
fish_bin:
	brew install fish

~/.config/fish/functions/fisher.fish:
	curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/completions/fisher.fish > ~/.config/fish/completions/fisher.fish
	curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish > ~/.config/fish/functions/fisher.fish

~/.config/fish/config.fish:
	ln -s ~/hiden/config.fish ~/.config/fish/config.fish

.PHONY: fish_plugins
fish_plugins:
	fish -c "fisher install oh-my-fish/theme-bobthefish 2m/fish-history-merge"
	curl https://raw.githubusercontent.com/docker/docker-ce/master/components/cli/contrib/completion/fish/docker.fish -o ~/.config/fish/completions/docker.fish
	curl https://raw.githubusercontent.com/docker/compose/master/contrib/completion/fish/docker-compose.fish -o ~/.config/fish/completions/docker-compose.fish
	if which aws; then fish -c "fisher install oh-my-fish/plugin-aws"; fi


.PHONY: set_shell
set_shell:
	@# Password will be prompted
	if ! grep -q "$(shell which fish)" /etc/shells; then echo $(shell which fish) | sudo tee -a /etc/shells; fi
	if [[ "$${SHELL}" != "$(shell which fish)" ]]; then chsh -s $(shell which fish); fi

### Vim related

.PHONY: vim
vim: ~/.vim_runtime vim-plug force_vimrc ;

~/.vim_runtime:
	git clone --depth=1 https://github.com/amix/vimrc.git ~/.vim_runtime

.PHONY: vim-plug
vim-plug:
	curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
		    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

.PHONY: force_vimrc
force_vimrc:
	@echo "\" This file is generated by ~/hiden/Makefile. Do not edit manually!" > ~/.vimrc
	@echo "" >> ~/.vimrc
	@cat ~/.vim_runtime/vimrcs/basic.vim >> ~/.vimrc
	@cat ~/hiden/.vimrc >> ~/.vimrc
	@echo "Open vim and run :PlugInstall to finish plugin install"

### SSH related

.PHONY: ssh
ssh: force_ssh_config /usr/local/bin/sshrc ~/.sshrc ~/.sshrc.d ~/.sshrc.d/.vimrc ;

# Using patched version
/usr/local/bin/sshrc:
	curl -Lo /usr/local/bin/sshrc https://raw.githubusercontent.com/taylorskalyo/sshrc/954d34ecd4761eb91f41cda0c54434b57ef4b6a3/sshrc
	chmod +x /usr/local/bin/sshrc

.PHONY: force_ssh_config
force_ssh_config:
	cat ~/hiden/.ssh/config_entry_point > ~/.ssh/config
	chmod 644 ~/.ssh/config

~/.sshrc:
	ln -Fs ~/hiden/.sshrc ~/.sshrc

~/.sshrc.d:
	mkdir -p ~/.sshrc.d

~/.sshrc.d/.vimrc:
	ln -Fs ~/.vimrc ~/.sshrc.d/.vimrc

### Fonts

.PHONY: install_fonts
install_fonts: ~/Library/Fonts/Source\ Code\ Pro\ for\ Powerline.otf ~/Library/Fonts/migmix-2m-bold.ttf ;

~/Library/Fonts/Source\ Code\ Pro\ for\ Powerline.otf:
	git clone https://github.com/powerline/fonts
	fonts/install.sh
	@echo "Re-login after this in order to reload font settings"
	rm -rf fonts

LATEST_MIGMIX = migmix-2m-20150712
~/Library/Fonts/migmix-2m-bold.ttf:
	curl -O http://jaist.dl.osdn.jp/mix-mplus-ipa/63544/$(LATEST_MIGMIX).zip
	unzip -q $(LATEST_MIGMIX).zip
	cp $(LATEST_MIGMIX)/migmix-2m-*.ttf ~/Library/Fonts/.
	@echo "Re-login after this in order to reload font settings"
	rm -rf $(LATEST_MIGMIX)*

### Other dot-files

.PHONY: misc
misc: ~/.gnupg/gpg-agent.conf ~/.config/git/ignore git_config ;

~/.gnupg/gpg-agent.conf:
	mkdir -p ~/.gnupg
	ln -s ~/hiden/.gnupg/gpg-agent.conf ~/.gnupg/gpg-agent.conf

~/.config/git/ignore:
	mkdir -p ~/.config/git
	ln -s ~/hiden/gitignore_global ~/.config/git/ignore

.PHONY: git_config
git_config:
	git config --global --replace-all init.templateDir ~/hiden/git_template
	git config --global --replace-all core.editor vim
	git config --global --replace-all user.name 'Yu Matsuzawa'
	git config --global --replace-all advice.detachedHead false
	git config --global --replace-all core.quotepath false
	git config --global --replace-all pull.ff only
	@echo ""
	@echo "MUST: Set git author email with 'git config --global user.email <email>'!"
	@echo ""
