#!/bin/sh

# HOWTOUSE: Save this file as '.git/hooks/prepare-commit-msg' in your repository,
#            and give Execution permission.

# NOTE: Be on branch begin with "<ticket #>_". e.g. "55555_this_is_branch_name".
# This script put ticket number on commit message, taken from branch name.
if [ "$2" = "" ] ; then
  # 'git commit' without '-m'. Open message editing Vim with ticket number in place.
  mv $1 $1.tmp
  printf "[`git symbolic-ref -q --short HEAD | sed -e 's/^\([^_]*\)_.*/\1/'`] \n" > $1
  cat $1.tmp >> $1
elif [ "$2" = "message" ] ; then
  # 'git commit -m "message"'. Ticket number automatically prepended.
  mv $1 $1.tmp
  printf "[`git symbolic-ref -q --short HEAD | sed -e 's/^\([^_]*\)_.*/\1/'`] " > $1
  cat $1.tmp >> $1
fi

# ENDNOTE: With '--amend' option, or template enabled, this does nothing.
#          You may edit regex pattern and/or reference command (in this case 'git symbolic-ref')
#           so as to fit your convention.
#          If the branch naming pattern is the same, this script works on any other repository.
