[aws]
disabled = true

[docker_context]
disabled = true

[package]
disabled = true

[shell]
disabled = false

[time]
disabled = false

[git_status]
# $stashedにそんなに興味がないので除いている
format = "([\\[$conflicted$deleted$renamed$modified$staged$untracke$ahead_behind\\]]($style) )"
