command_timeout = 1500

[aws]
disabled = true

[docker_context]
disabled = true

[package]
disabled = true

[elixir]
disabled = true

[nodejs]
disabled = true

[ruby]
disabled = true

[elm]
disabled = true

[shell]
disabled = false

[time]
disabled = false

[git_status]
# $stashedにそんなに興味がないので除いている
format = "([\\[$conflicted$deleted$renamed$modified$staged$untracke$ahead_behind\\]]($style) )"

[git_commit]
only_detached = false

[bun]
disabled = true

[terraform]
disabled = true

[cmd_duration]
show_notifications = true
min_time_to_notify = 10_000
notification_timeout = 3_000
