#!/usr/bin/env bash
set -euo pipefail
if [ -f mix.exs ]; then
  PORT=7878 mix test
fi
if [ -f package.json ]; then
  if npm run | grep '^  test$' > /dev/null; then
    npm test
  fi
fi
if [ -f elm.json ]; then
  if grep 'elm-explorations/test' > /dev/null; then
    elm-test
  fi
fi
